### PR TITLE
New renamed repo.

### PR DESCRIPTION
**Pull request by BHObserver**
Created a new repository with a proper name. Updated the README file.

Prev PR: https://github.com/BHObserver/hello_microverse_project/pull/2

### CODE REVIEW

**Comment by topeogunleye** [comment]
> Created a new repository with a proper name. Updated the README file.

@BHObserver, You can  mention the old pr to the new pr by simply writing the link underneath your description here 

## EXAMPLE
Prev PR: https://github.com/BHObserver/hello_microverse_project/pull/2

**Comment by BHObserver** [comment]
Okay.. I got it.. Thanks a lot.

**Comment by BHObserver** [comment]
Thanks, I edited the comment and mention old PR.

**Review by Cabraham1 — APPROVED** [review]
Hi @BHObserver  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
